version: '2.0'
services:
  spinplast:
    build:
      context: .
    ports:
    - "8000:8000"

    volumes:
    - .:/spinplast

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
