# Generated by Django 3.2.12 on 2023-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ikons', models.CharField(max_length=500, verbose_name='иконка соцсети')),
                ('network_image', models.ImageField(blank=True, upload_to='network_image', verbose_name='картинка соцсети')),
                ('url_network', models.TextField(blank=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'социальные сети',
                'verbose_name_plural': 'социальные сети',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_new', models.CharField(max_length=200, verbose_name='заголовок новости')),
                ('body_new', models.TextField(blank=True, default='', verbose_name='текст неовости')),
                ('image_new', models.ImageField(blank=True, upload_to='image_new', verbose_name='картинка новости')),
            ],
            options={
                'verbose_name': 'новости',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='Onas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_onas1', models.CharField(max_length=500, verbose_name='заголовок')),
                ('title_onas2', models.CharField(blank=True, max_length=500, verbose_name='второй заголовок')),
                ('body_onas', models.TextField(blank=True, default='', verbose_name='текст')),
                ('image_uslugi', models.ImageField(blank=True, upload_to='home', verbose_name='главное фото')),
            ],
            options={
                'verbose_name': 'онас',
                'verbose_name_plural': 'онас',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='PodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_podcategory', models.CharField(max_length=200, verbose_name='подкатегория')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('image_podcategory', models.ImageField(blank=True, upload_to='podkategory')),
                ('product', models.ManyToManyField(to='polls.Product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегория',
                'ordering': ['title_podcategory'],
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_contact', models.CharField(max_length=200, verbose_name='контакт')),
                ('body_contact', models.TextField(blank=True, default='', verbose_name='текст контакта')),
                ('adress_one_contact', models.TextField(blank=True, default='', verbose_name='адрес')),
                ('tel', models.CharField(max_length=200, verbose_name='телефон')),
                ('web', models.TextField(blank=True, default='', verbose_name='email')),
                ('network_ikons', models.ManyToManyField(blank=True, default='', to='polls.Network', verbose_name='иконки соцсетей')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакт',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=200, verbose_name='категория')),
                ('slug_category', models.SlugField(verbose_name='slug')),
                ('image_catalog', models.ImageField(blank=True, upload_to='category/', verbose_name='фото категории')),
                ('podcategory', models.ManyToManyField(to='polls.PodCategory', verbose_name='подкаталог')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title_category'],
                'index_together': {('id', 'slug_category')},
            },
        ),
    ]
