# Generated by Django 3.2.12 on 2023-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20230802_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carusel_home_page',
            field=models.BooleanField(default=False, verbose_name='карусель на главной странице'),
        ),
    ]
