# Generated by Django 3.2.12 on 2023-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product_carusel_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_baner', models.CharField(max_length=500, verbose_name='баннер')),
                ('image_banner', models.ImageField(blank=True, upload_to='network_image', verbose_name='картинка баннер')),
                ('text_banner', models.TextField(blank=True, verbose_name='текст баннера')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
            },
        ),
    ]
