# Generated by Django 3.2.12 on 2023-08-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
