# Generated by Django 3.2.12 on 2023-08-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='baher_glav1',
            field=models.BooleanField(default=True, verbose_name='баннер справа от карусели'),
        ),
        migrations.AddField(
            model_name='product',
            name='reklam_text',
            field=models.TextField(blank=True, verbose_name='Рекламный текст'),
        ),
        migrations.AddField(
            model_name='product',
            name='reklam_title',
            field=models.TextField(blank=True, verbose_name='Рекламный заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='skidka',
            field=models.TextField(blank=True, verbose_name='размер скидки'),
        ),
    ]
