# Generated by Django 3.2.12 on 2023-08-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20230803_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_for_banner',
            field=models.ImageField(blank=True, upload_to='banner/', verbose_name='фото для баннера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='baher_glav1',
            field=models.BooleanField(default=False, verbose_name='баннер справа от карусели'),
        ),
    ]
