# Generated by Django 3.2.12 on 2023-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20230803_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_carusel', models.CharField(max_length=500, verbose_name='название карусели')),
                ('carusel_image', models.ImageField(blank=True, upload_to='network_image', verbose_name='картинка карусель')),
                ('carusel_text', models.TextField(blank=True, verbose_name='текст для карусели')),
            ],
            options={
                'verbose_name': 'фото карусель',
                'verbose_name_plural': 'фото карусель',
            },
        ),
    ]
