# Generated by Django 3.2.12 on 2023-08-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_product_big_hit_prodaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_recomend',
            field=models.BooleanField(default=False, verbose_name='Большая фото Рекомендуемого товара'),
        ),
    ]
