# Generated by Django 3.2.12 on 2023-08-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_product_big_recomend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_new_tovar',
            field=models.BooleanField(default=False, verbose_name='Большая фото новый товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_tovar',
            field=models.BooleanField(default=False, verbose_name='Новый товар'),
        ),
    ]
