# Generated by Django 3.2.12 on 2023-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20230803_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specpredlojenie',
            field=models.BooleanField(default=False, verbose_name='спецпредложение главная стр'),
        ),
    ]
