# Generated by Django 3.2.12 on 2023-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_product_specpredlojenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='samie_prodavaemie',
            field=models.BooleanField(default=False, verbose_name='самые продаваемые на главной странице'),
        ),
    ]
