# Generated by Django 3.2.12 on 2023-08-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_product_hit_prodaj2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_tovar2',
            field=models.BooleanField(default=False, verbose_name='Новый товар2'),
        ),
    ]
