# Generated by Django 3.2.12 on 2023-08-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20230804_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
