# Generated by Django 3.2.12 on 2023-08-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kategory', models.CharField(max_length=200, verbose_name='категория')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('image_katalog', models.ImageField(blank=True, upload_to='kategory/', verbose_name='фото категории')),
                ('product', models.ManyToManyField(to='polls.Product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title_kategory'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
