# Generated by Django 3.2.12 on 2023-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_kategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.CharField(max_length=500, verbose_name='вопрос')),
                ('body_question', models.TextField(blank=True, default='', verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'вопросы',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.AddField(
            model_name='onas',
            name='question',
            field=models.ManyToManyField(to='polls.Question', verbose_name='вопрос'),
        ),
    ]
