# Generated by Django 3.2.12 on 2023-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20230810_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sertificat', models.CharField(max_length=500, verbose_name='заголовок сертификата')),
                ('image_sertificat', models.ImageField(blank=True, upload_to='sertifacats', verbose_name='фото сертификата')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификаты',
            },
        ),
        migrations.AddField(
            model_name='onas',
            name='image_sertifacat',
            field=models.ManyToManyField(to='polls.Sertificat', verbose_name='сертификаты'),
        ),
    ]
